### ISSUE TITLE
上线流程

### ISSUE THREAD

**Issue by thbgh** [simplefeel/react-node-learn#1]
请教一下这样吊炸天的项目如何上线?

**Comment by simplefeel** [comment]
> 请教一下这样吊炸天的项目如何上线?

大兄弟，你这倒是问到我了啊~

项目上线，有很多环节呀！我简单说下吧：

1.前端
代码测试、编译、打包

2.后端
搭建一个node api服务用来处理数据；
搭建一个数据库（比如mongodb）用来存储数据；
搭建一个资源服务器用来部署代码

其它自行google吧！

**Comment by thbgh** [comment]
> > 请教一下这样吊炸天的项目如何上线?
> 
> 大兄弟，你这倒是问到我了啊~
> 
> 项目上线，有很多环节呀！我简单说下吧：
> 
> 1.前端
> 代码测试、编译、打包
> 
> 2.后端
> 搭建一个node api服务用来处理数据；
> 搭建一个数据库（比如mongodb）用来存储数据；
> 搭建一个资源服务器用来部署代码
> 
> 其它自行google吧！

最终还是得拆开来分别上线.

不过我喜欢这个项目,你真棒!
